### ISSUE TITLE
SUGGESTION: Is die required here?

### ISSUE THREAD

**Issue by georgehanson** [midnite81/laravel-base#11]
https://github.com/midnite81/laravel-base/blob/4b45e05f35427dcef923c2a6f3f7a959fb63d4d1/src/Commands/Users/ResetUsersPassword.php#L92

I'm not sure if `die()` is required here. If an exception is thrown, will it not stop the execution of the command?

**Comment by midnite81** [comment]
Nope, but then again it's a development branch - so it would be checked before putting to master.
